### Web Scrappng: saving data into Csv and Excel

<h4>1.Import Libraries

In [7]:
import bs4
import urllib.request
from urllib.request import urlopen
from bs4 import BeautifulSoup as soup
import csv

<h4>2.Load the Html Code from url 
<h4>2.I. write to csv files

In [8]:
filename = 'Music_Distributions_Ratings.csv'
f = open(filename, 'w',newline = '')
music = csv.writer(f) #to write into cvs file

html = urlopen('https://en.wikipedia.org/wiki/List_of_largest_recorded_music_markets')
bsobj = soup(html.read())
tbody = bsobj('table',{'class':'wikitable plainrowheaders sortable'})[3].findAll('tr')
tbody
xl = [] #to write into excel file
for row in tbody:
    cols = row.findChildren(recursive = False)
    cols = [element.text.strip() for element in cols]
    music.writerow(cols)
    xl.append(cols)
    print(cols)

['Rank', 'Market', 'Retail valueUS$ (millions)', 'Physical', 'Digital', 'Performance rights', 'Synchronization']
['1', 'United States', '5,916.1', '15%', '75%', '7%', '3%']
['2', 'Japan', '2,727.5', '72%', '21%', '5%', '1%']
['3', 'Germany', '1,323.1', '43%', '36%', '20%', '1%']
['4', 'United Kingdom', '1,310.7', '30%', '50%', '18%', '2%']
['5', 'France', '925.1', '36%', '34%', '27%', '3%']
['6', 'South Korea', '494.4', '37%', '59%', '4%', '0%']
['7', 'Canada', '437.2', '21%', '65%', '14%', '1%']
['8', 'Australia', '412.9', '19%', '68%', '11%', '2%']
['9', 'Brazil', '295.8', '5%', '60%', '34%', '0%']
['10', 'China', '292.3', '3%', '90%', '7%', '0%']
['11', 'Netherlands', '269.5', '22%', '50%', '27%', '0%']
['12', 'Italy', '247.9', '39%', '36%', '22%', '3%']
['13', 'Spain', '205.8', '26%', '49%', '24%', '2%']
['14', 'Sweden', '199.5', '10%', '72%', '17%', '1%']
['15', 'Norway', '139.0', '9%', '71%', '19%', '1%']
['16', 'Denmark', '137.9', '7%', '56%', '36%', '1%']
['17', 'Switzerland', '137.8', '27%', '52%', '21%', '0%']
['18', 'Mexico', '137.0', '15%', '79%', '4%', '1%']
['19', 'India', '130.7', '7%', '78%', '9%', '6%']
['20', 'Argentina', '130.0', '8%', '31%', '60%', '1%']
['', 'Global total', '17,270', 'n/a', 'n/a', 'n/a', 'n/a']

In [9]:
import os
os.getcwd()

'C:\\Users\\user\\Data Analysis Using Python(Project)'

3.To write to excel file

In [10]:
xl

[['Rank',
  'Market',
  'Retail valueUS$ (millions)',
  'Physical',
  'Digital',
  'Performance rights',
  'Synchronization'],
 ['1', 'United States', '5,916.1', '15%', '75%', '7%', '3%'],
 ['2', 'Japan', '2,727.5', '72%', '21%', '5%', '1%'],
 ['3', 'Germany', '1,323.1', '43%', '36%', '20%', '1%'],
 ['4', 'United Kingdom', '1,310.7', '30%', '50%', '18%', '2%'],
 ['5', 'France', '925.1', '36%', '34%', '27%', '3%'],
 ['6', 'South Korea', '494.4', '37%', '59%', '4%', '0%'],
 ['7', 'Canada', '437.2', '21%', '65%', '14%', '1%'],
 ['8', 'Australia', '412.9', '19%', '68%', '11%', '2%'],
 ['9', 'Brazil', '295.8', '5%', '60%', '34%', '0%'],
 ['10', 'China', '292.3', '3%', '90%', '7%', '0%'],
 ['11', 'Netherlands', '269.5', '22%', '50%', '27%', '0%'],
 ['12', 'Italy', '247.9', '39%', '36%', '22%', '3%'],
 ['13', 'Spain', '205.8', '26%', '49%', '24%', '2%'],
 ['14', 'Sweden', '199.5', '10%', '72%', '17%', '1%'],
 ['15', 'Norway', '139.0', '9%', '71%', '19%', '1%'],
 ['16', 'Denmark', '137.9', '7%', '56%', '36%', '1%'],
 ['17', 'Switzerland', '137.8', '27%', '52%', '21%', '0%'],
 ['18', 'Mexico', '137.0', '15%', '79%', '4%', '1%'],
 ['19', 'India', '130.7', '7%', '78%', '9%', '6%'],
 ['20', 'Argentina', '130.0', '8%', '31%', '60%', '1%'],
 ['', 'Global total', '17,270', 'n/a', 'n/a', 'n/a', 'n/a']]

In [11]:
import pandas as pd
df = pd.DataFrame(data =xl)
df

,0,1,2,3,4,5,6
0,Rank,Market,Retail valueUS$ (millions),Physical,Digital,Performance rights,Synchronization
1,1,United States,"5,916.1",15%,75%,7%,3%
2,2,Japan,"2,727.5",72%,21%,5%,1%
3,3,Germany,"1,323.1",43%,36%,20%,1%
4,4,United Kingdom,"1,310.7",30%,50%,18%,2%
5,5,France,925.1,36%,34%,27%,3%
6,6,South Korea,494.4,37%,59%,4%,0%
7,7,Canada,437.2,21%,65%,14%,1%
8,8,Australia,412.9,19%,68%,11%,2%
9,9,Brazil,295.8,5%,60%,34%,0%
10,10,China,292.3,3%,90%,7%,0%
11,11,Netherlands,269.5,22%,50%,27%,0%
12,12,Italy,247.9,39%,36%,22%,3%
13,13,Spain,205.8,26%,49%,24%,2%
14,14,Sweden,199.5,10%,72%,17%,1%
15,15,Norway,139.0,9%,71%,19%,1%
16,16,Denmark,137.9,7%,56%,36%,1%
17,17,Switzerland,137.8,27%,52%,21%,0%
18,18,Mexico,137.0,15%,79%,4%,1%
19,19,India,130.7,7%,78%,9%,6%
20,20,Argentina,130.0,8%,31%,60%,1%
21,,Global total,"17,270",n/a,n/a,n/a,n/a

3. Now, let's run it into Excel format.

In [12]:
df.to_excel('Music_Distributions_Ratings.xlsx', index= False,header =False)
print("Spreadsheet saved.")

Spreadsheet saved.

### THE END